### ISSUE TITLE
Capture images using Camera

### ISSUE THREAD

**Issue by saiadityaviswanadham** [Umesh-01/Python-Assistant#14]
To capture the image using webcam using Python Assistant, ecapture module of python is implemented

**Comment by saiadityaviswanadham** [comment]
Please assign this issue to me @Umesh-01

**Comment by Rajkushwaha26** [comment]
"Hi, I am Raj Kushwaha, a contributor to girls script foundation 2022. I would like to work on this issue.Can you allow me to add my skills to this project.

**Comment by anandxkumar** [comment]
Fixed in #16
