### ISSUE TITLE
Adding "What is the price of ....." Feature

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [Umesh-01/Python-Assistant#28]
This feature will help users know the current price of any item just by asking the assistant.

Eg: What is the current price of PS5
Ouput: "The price of PS5 in India is Rs. 24999"

**Comment by Sabyasachi-Seal** [comment]
I am a GSSoC '22 Participant. 

Please assign me this so that I could start working on this.

**Comment by Umesh-01** [comment]
> This feature will help users know the current price of any item just by asking the assistant.
> 
> Eg: What is the current price of PS5 
> Ouput: "The price of PS5 in India is Rs. 24999"

Yes @Sabyasachi-Seal you can start working on it.

**Comment by Sabyasachi-Seal** [comment]
Thank You :)

**Comment by Sabyasachi-Seal** [comment]
Issue Resolved and PR merged.

https://github.com/Umesh-01/Python-Assistant/pull/51/commits/123cc16eb42d4461e90fe46c9a79a3fd8d22ac6e
