### ISSUE TITLE
Want to add a password manager

### ISSUE THREAD

**Issue by iamrahulmahato** [Umesh-01/Python-Assistant#36]
want to make a password manager where user can stored and manage password

As a participant of GSsOC '22, I would like to work on it

**Comment by TheCreaToR-01** [comment]
Great Idea

**Comment by Umesh-01** [comment]
@iamrahulmahato How are you going to implement this feature, can you elaborate??

**Comment by Phoenix-031** [comment]
@Umesh-01 I have made a password manager gui with tkinter which uses a sqlit3 database and stores passwords offline in a .db file we can add that to this project which can make this functionality possible

I can work on this as a part of GSSOC 22'

**Comment by iamrahulmahato** [comment]
@Umesh-01 
I will make a console app with the help of python where i use cryptography module of python to encrypt and decrypt password the password

function:
password will be  encrypt
create the password
load the existing password
create new password file
load existing password file
add a new password
get a new password
