### ISSUE TITLE
Want to Add Python Virtual Alexa.

### ISSUE THREAD

**Issue by Avik-creator** [Umesh-01/Python-Assistant#38]
## Feature Request

- Want to a Virtual Assistant Using Python
- It will be a fun project
- A GSSOC 2022 Contributor Avik Mukherjee

**Comment by Umesh-01** [comment]
@Avik-creator this is also a voice assistant like alexa. can you explain what you want to add??

**Comment by Avik-creator** [comment]
@Umesh-01 just some basic features like opening YouTube, Opening some app, Getting Time etc

**Comment by Umesh-01** [comment]
these features are already there in Python Assistant.

**Comment by Umesh-01** [comment]
@Avik-creator kindly go through the project once, probably you will find out something to contribute.
