### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by UDAYAGIRICHARAN** [Umesh-01/Python-Assistant#41]
Feature Request
Want to add Virtual Assistant Using Python
adding multiple futures with commend like saying jokes,time etc
A GSSOC 2022 Contributor CHARAN KUMAR UDAYGIRI

**Comment by Umesh-01** [comment]
@UDAYAGIRICHARAN these features are already available. You can go through the project, may be you can find out something to contribute on.
