### ISSUE TITLE
Simple GUI to help non tech users use it 

### ISSUE THREAD

**Issue by Yasien99** [Umesh-01/Python-Assistant#44]
- Hi, As a GSSOC 22 contributor I want to make the program more useable by non-tech people who has no experience with the command line, so I think making GUI will make it simple to use.

Can you please assign it to me?

**Comment by Yasien99** [comment]
![image](https://user-images.githubusercontent.com/55417069/156889650-3c794e32-51d7-4e9a-95dc-1b88fbee2c55.png)

This is what I was thinking of, I found this photo of another open-source voice-assistant

**Comment by Umesh-01** [comment]
Yes @Yasien99 good idea, go for it.
