### ISSUE TITLE
Works Slow

### ISSUE THREAD

**Issue by harish795r** [Umesh-01/Python-Assistant#5]
Hey,
U did a great Job making this
but It Works Too Slow I guess The programming language is the problem try to make it in C or java it would be more fast

**Comment by Umesh-01** [comment]
Hey @harish795r 
It's true that C, CPP and Java are faster and more efficient than Python but I don't think that these libraries are available in these languages. And I haven't tried if any alternative libraries are present there or not. 
If it is possible and you want to work on it then go ahead. You can create a Java or CPP or C version for this project. 👍 
I will assign this task to you... 🙂

**Comment by Umesh-01** [comment]
@harish795r are u working on this??

**Comment by harish795r** [comment]
> @harish795r are u working on this??
> 

No, sorry
