### ISSUE TITLE
"_name_" is not defined

### ISSUE THREAD

**Issue by Skyere** [Umesh-01/Python-Assistant#6]
![image](https://user-images.githubusercontent.com/70713060/124328326-17723180-db92-11eb-95ec-0deac4f08716.png)

**Comment by Umesh-01** [comment]
@Skyere use double underscores before and after the **name**

Like this- `if __name__ == '__main__':`

**Comment by Umesh-01** [comment]
I hope it will help you, if you face any other issue just comment below...
