### ISSUE TITLE
After opening Pa.py, nothing was happen. Where is my trouble?

### ISSUE THREAD

**Issue by Skyere** [Umesh-01/Python-Assistant#7]

**Comment by Umesh-01** [comment]
@Skyere I already told you check #6 
And don't create new issues, it's just you are facing some errors while running this PA.py file there is no need to create such issues
Only comment below these issues..

**Comment by Skyere** [comment]
I have fixed #6, but PA.py still stopped after start without any errors

**Comment by Skyere** [comment]
Okay, I fixed it. But now I have another issue: The assistent hasn't hear me. Could you help me?

**Comment by Umesh-01** [comment]
@Skyere which IDE you are using??

**Comment by Umesh-01** [comment]
have you installed all the libraries required??

**Comment by Skyere** [comment]
Yes, I installed all libraries. I'm using vs code

**Comment by Umesh-01** [comment]
Is there any error while running the program or any highlighted text??

**Comment by Skyere** [comment]
Without any errors or warning

**Comment by Skyere** [comment]
Only "Listening..."

**Comment by Umesh-01** [comment]
can you send me a screenshot??

**Comment by Skyere** [comment]
![image](https://user-images.githubusercontent.com/70713060/124359228-af245e00-dc2c-11eb-9f3a-852b9e7e783f.png)

**Comment by Skyere** [comment]
I tried launc on console too. But recieved the same

**Comment by Umesh-01** [comment]
@Skyere try this !!

write these lines after `engine = pyttsx3.init()`
```python
voices = engine.getProperty('voices')       
engine.setProperty('voice', voices[1])
```

**Comment by Skyere** [comment]
still the same error

**Comment by Umesh-01** [comment]
is that voice assistant speaking??

**Comment by Skyere** [comment]
Yes, I hear this text
![image](https://user-images.githubusercontent.com/70713060/124361614-82764380-dc38-11eb-827d-c3f1d9e29d69.png)

**Comment by Umesh-01** [comment]
then try to speak something in a slient environment, maybe it will recognize...

use headphones (with microphone) if possible...

**Comment by Umesh-01** [comment]
sometimes due to noisy environment it stuck at listening and doesn't go to recognize the voice...

**Comment by Skyere** [comment]
I'm tried use this to check my microphone
![image](https://user-images.githubusercontent.com/70713060/124362150-00881980-dc3c-11eb-954e-1e1cc281af04.png)

**Comment by Skyere** [comment]
And this one recognize my voice
![image](https://user-images.githubusercontent.com/70713060/124362171-1dbce800-dc3c-11eb-9b58-848f8ce080ab.png)

**Comment by Umesh-01** [comment]
Hello @Skyere 
I am not getting what error you are facing !!

what should can I do??

**Comment by Umesh-01** [comment]
It's working for me, I have tried to run the same code...

Just there was the only error for underscores before and after both `name` and `main` in this line
```python
if __name__ == '__main__':
```
